language: r
r:
  - release
  - devel
sudo: false
cache: packages

r_packages:
  - knitr
  - devtools
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'

notifications:
  email:
    - maxime.turgeon@mail.mcgill.ca
